services:
  api:
    build:
      context: flask-server
      dockerfile: Dockerfile
    image: goalzilla-flask
  client:
    build:
      context: goalzilla-react
      dockerfile: Dockerfile
    image: goalzilla-react
    ports:
      - "3000:3000"